import json

# data = {"alert_id":40,"Title":"Test Alert 69","description":"Suspecious Activity detected 1","dateTime":"02:40:50.804976","proofImage":"/media/static/proofImages/background_image_for_ai_based_traffic_sign_detec.jpg","status":"pending","feedback":False,"feedbackMsg":None,"summary":None,"policeStation_id":2},{"alert_id":41,"Title":"Test Alert 69","description":"Suspecious Activity detected 1","dateTime":"02:41:15.020793","proofImage":"/media/static/proofImages/background_image_for_ai_based_traffic_sign_detec_9Atlb1C.jpg","status":"pending","feedback":False,"feedbackMsg":None,"summary":None,"policeStation_id":2},{"alert_id":42,"Title":"Test Alert 69","description":"Suspecious Activity detected 1","dateTime":"02:41:33.039060","proofImage":"/media/static/proofImages/background_image_for_ai_based_traffic_sign_detec_cqLVpnY.jpg","status":"pending","feedback":False,"feedbackMsg":None,"summary":None,"policeStation_id":2},{"alert_id":43,"Title":"Test Alert 69","description":"Suspecious Activity detected 1","dateTime":"02:41:37.797495","proofImage":"/media/static/proofImages/background_image_for_ai_based_traffic_sign_detec_YgMf587.jpg","status":"pending","feedback":False,"feedbackMsg":None,"summary":None,"policeStation_id":2},{"alert_id":44,"Title":"Test Alert 69","description":"Suspecious Activity detected 1","dateTime":"02:41:42.448520","proofImage":"/media/static/proofImages/background_image_for_ai_based_traffic_sign_detec_AZ25EeL.jpg","status":"pending","feedback":False,"feedbackMsg":None,"summary":None,"policeStation_id":2},{"alert_id":45,"Title":"Test Alert 69","description":"Suspecious Activity detected 1","dateTime":"02:41:44.588081","proofImage":"/media/static/proofImages/background_image_for_ai_based_traffic_sign_detec_rFayMzl.jpg","status":"pending","feedback":False,"feedbackMsg":None,"summary":None,"policeStation_id":2}
data = {"alert_id":40,"Title":"Test Alert 69","description":"Suspecious Activity detected 1","dateTime":"02:40:50.804976","proofImage":"/media/static/proofImages/background_image_for_ai_based_traffic_sign_detec.jpg","status":"pending","feedback":false,"feedbackMsg":null,"summary":null,"policeStation_id":2},{"alert_id":41,"Title":"Test Alert 69","description":"Suspecious Activity detected 1","dateTime":"02:41:15.020793","proofImage":"/media/static/proofImages/background_image_for_ai_based_traffic_sign_detec_9Atlb1C.jpg","status":"pending","feedback":false,"feedbackMsg":null,"summary":null,"policeStation_id":2},{"alert_id":42,"Title":"Test Alert 69","description":"Suspecious Activity detected 1","dateTime":"02:41:33.039060","proofImage":"/media/static/proofImages/background_image_for_ai_based_traffic_sign_detec_cqLVpnY.jpg","status":"pending","feedback":false,"feedbackMsg":null,"summary":null,"policeStation_id":2},{"alert_id":43,"Title":"Test Alert 69","description":"Suspecious Activity detected 1","dateTime":"02:41:37.797495","proofImage":"/media/static/proofImages/background_image_for_ai_based_traffic_sign_detec_YgMf587.jpg","status":"pending","feedback":false,"feedbackMsg":null,"summary":null,"policeStation_id":2},{"alert_id":44,"Title":"Test Alert 69","description":"Suspecious Activity detected 1","dateTime":"02:41:42.448520","proofImage":"/media/static/proofImages/background_image_for_ai_based_traffic_sign_detec_AZ25EeL.jpg","status":"pending","feedback":false,"feedbackMsg":null,"summary":null,"policeStation_id":2},{"alert_id":45,"Title":"Test Alert 69","description":"Suspecious Activity detected 1","dateTime":"02:41:44.588081","proofImage":"/media/static/proofImages/background_image_for_ai_based_traffic_sign_detec_rFayMzl.jpg","status":"pending","feedback":false,"feedbackMsg":null,"summary":null,"policeStation_id":2}

if "false" in data:
    updated_data = data.replace("flase","False")
    updated_data = updated_data.replace("null","None")

para = []
for key, value in updated_data.items():
    para.append(str(key) + ': ' + str(value))

print(para)